### ISSUE TITLE
About experiments

### ISSUE THREAD

**Issue by lizhh268** [yangheng95/InstOptima#1]
Hello, I noticed that T5 is used as the model for performance evaluation in the code, while ChatGPT is mentioned as the model used for evolving instructions. This differs somewhat from the evaluation using ChatGPT mentioned (evolving and evaluation) in the paper.

**Comment by yangheng95** [comment]
These additional experiments are not included, but sure will be released in future. Never mind, it is not hard to implement this variant via some modifications of the evaluation code.

**Comment by lizhh268** [comment]
Ok, thank you for your explanation.
